# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_NSS_DRIVERS_LAB02_EX02)	+= ex2/my-awesome-driver.o
obj-$(CONFIG_NSS_DRIVERS_LAB02_EX03)	+= ex3/led.o
obj-$(CONFIG_NSS_DRIVERS_LAB02_EX04)	+= ex4/led-math.o
