# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_NSS_DRIVERS_LAB01_EX01)	+= # TODO: compile hello.c
obj-$(CONFIG_NSS_DRIVERS_LAB01_EX04)	+= ex4/hello_name.o
obj-$(CONFIG_NSS_DRIVERS_LAB01_EX05)	+= ex5/imx8mq_chardev.o
